// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");
var EditDistance = require("./EditDistance.js");

var t1 = EditDistance.levenshtein("bookling", "back");

console.log(t1);

var results = [t1 === 2];

function finalResult(param) {
  return Belt_Array.reduceU(results, (function (acc, result) {
                if (acc) {
                  return result;
                } else {
                  return false;
                }
              }), param);
}

var Levenshtein = {
  t1: t1,
  results: results,
  finalResult: finalResult
};

console.log(results);

exports.Levenshtein = Levenshtein;
/* t1 Not a pure module */
