// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var EditDistance = require("./EditDistance.js");

var t1 = EditDistance.levenshtein("back", "books");

var t2 = EditDistance.levenshtein("books", "back");

var data = [
  t1,
  t2
];

var expected = [
  3,
  3
];

var result = Caml_obj.caml_equal(data, expected);

console.log([
      result,
      data
    ]);

var Levenshtein = {
  t1: t1,
  t2: t2,
  data: data,
  expected: expected,
  result: result
};

var t1$1 = EditDistance.damerauLevenshtein3(undefined, "back", "books");

var t2$1 = EditDistance.levenshtein("books", "back");

var data$1 = [
  t1$1,
  t2$1
];

var expected$1 = [
  3,
  3
];

var result$1 = Caml_obj.caml_equal(data$1, expected$1);

console.log([
      result$1,
      data$1
    ]);

var DamerauLevenshtein = {
  t1: t1$1,
  t2: t2$1,
  data: data$1,
  expected: expected$1,
  result: result$1
};

exports.Levenshtein = Levenshtein;
exports.DamerauLevenshtein = DamerauLevenshtein;
/* t1 Not a pure module */
